'use strict';
/**
 * Promptaria source registry.
 * `trust` (0-100) feeds the quality score. `limit` caps items per run.
 * Everything here is admin-facing metadata; the public site never shows it.
 */
module.exports = [
  {
    key: 'awesome-chatgpt-prompts',
    name: 'Awesome ChatGPT Prompts',
    home_url: 'https://github.com/f/awesome-chatgpt-prompts',
    kind: 'csv',
    trust: 95,
    license: 'CC0-1.0',
    fetchUrl: 'https://raw.githubusercontent.com/f/awesome-chatgpt-prompts/main/prompts.csv',
    itemUrlBase: 'https://github.com/f/awesome-chatgpt-prompts/blob/main/prompts.csv',
    csv: { title: 'act', body: 'prompt' },
  },
  {
    key: 'chatgpt-system-prompts',
    name: 'ChatGPT System Prompts (mustvlad)',
    home_url: 'https://github.com/mustvlad/ChatGPT-System-Prompts',
    kind: 'github-files',
    trust: 85,
    license: 'MIT',
    repo: 'mustvlad/ChatGPT-System-Prompts',
    branch: 'main',
    pathPattern: '^prompts/.+\\.md$',
    limit: 60,
  },
  {
    key: 'awesome-prompts-gptstore',
    name: 'Awesome Prompts (GPT Store leaders)',
    home_url: 'https://github.com/ai-boost/awesome-prompts',
    kind: 'github-files',
    trust: 88,
    license: 'CC0-1.0',
    repo: 'ai-boost/awesome-prompts',
    branch: 'main',
    pathPattern: '^prompts/.+\\.(md|txt)$',
    limit: 90,
  },
  {
    key: 'linexjlin-gpts',
    name: 'GPTs Leaked Prompts (linexjlin)',
    home_url: 'https://github.com/linexjlin/GPTs',
    kind: 'github-files',
    trust: 80,
    license: 'MIT',
    repo: 'linexjlin/GPTs',
    branch: 'main',
    pathPattern: '^prompts/.+\\.md$',
    limit: 80,
  },
  {
    key: 'llm-prompt-library',
    name: 'LLM Prompt Library (abilzerian)',
    home_url: 'https://github.com/abilzerian/LLM-Prompt-Library',
    kind: 'github-files',
    trust: 84,
    license: 'MIT',
    repo: 'abilzerian/LLM-Prompt-Library',
    branch: 'main',
    pathPattern: '^prompts/.+\\.md$',
    limit: 70,
  },
  {
    key: 'ai-tools-system-prompts',
    name: 'System Prompts of AI Tools (x1xhlol)',
    home_url: 'https://github.com/x1xhlol/system-prompts-and-models-of-ai-tools',
    kind: 'github-files',
    trust: 78,
    license: 'GPL-3.0',
    repo: 'x1xhlol/system-prompts-and-models-of-ai-tools',
    branch: 'main',
    pathPattern: '\\.(txt|md)$',
    limit: 40,
  },
  {
    key: 'awesome-claude-prompts',
    name: 'Awesome Claude Prompts',
    home_url: 'https://github.com/langgptai/awesome-claude-prompts',
    kind: 'markdown',
    trust: 90,
    license: 'MIT',
    fetchUrl: 'https://raw.githubusercontent.com/langgptai/awesome-claude-prompts/main/README.md',
    anchorBase: 'https://github.com/langgptai/awesome-claude-prompts',
    defaultTags: ['claude'],
    limit: 120,
  },
  {
    key: 'dev-chatgpt-prompts',
    name: 'Dev ChatGPT Prompts (PickleBoxer)',
    home_url: 'https://github.com/PickleBoxer/dev-chatgpt-prompts',
    kind: 'markdown',
    trust: 82,
    license: 'MIT',
    fetchUrl: 'https://raw.githubusercontent.com/PickleBoxer/dev-chatgpt-prompts/master/README.md',
    anchorBase: 'https://github.com/PickleBoxer/dev-chatgpt-prompts',
    defaultTags: ['developers'],
    limit: 80,
  },
  {
    key: 'data-science-prompts',
    name: 'ChatGPT Data Science Prompts',
    home_url: 'https://github.com/travistangvh/ChatGPT-Data-Science-Prompts',
    kind: 'markdown',
    trust: 80,
    license: 'MIT',
    fetchUrl: 'https://raw.githubusercontent.com/travistangvh/ChatGPT-Data-Science-Prompts/main/README.md',
    anchorBase: 'https://github.com/travistangvh/ChatGPT-Data-Science-Prompts',
    defaultTags: ['data-science'],
    limit: 80,
  },
  {
    key: 'chatgpt-shortcut',
    name: 'ChatGPT Shortcut',
    home_url: 'https://www.aishort.top',
    kind: 'json-cards',
    trust: 86,
    license: 'MIT',
    fetchUrl: 'https://raw.githubusercontent.com/rockbenben/ChatGPT-Shortcut/main/src/data/prompt_en.json',
    itemUrlBase: 'https://www.aishort.top/en',
    json: { nestedKey: 'en', title: 'title', body: 'prompt', tags: 'tags' },
    limit: 300,
  },
  {
    key: 'mr-ranedeer',
    name: 'Mr. Ranedeer AI Tutor',
    home_url: 'https://github.com/JushBJJ/Mr.-Ranedeer-AI-Tutor',
    kind: 'single',
    trust: 88,
    license: 'MIT',
    fetchUrl: 'https://raw.githubusercontent.com/JushBJJ/Mr.-Ranedeer-AI-Tutor/main/Mr_Ranedeer.txt',
    singleTitle: 'Mr. Ranedeer — Personalized AI Tutor',
    defaultTags: ['education', 'tutor'],
  },
  {
    key: 'greataiprompts',
    name: 'GreatAIPrompts',
    home_url: 'https://www.greataiprompts.com',
    kind: 'html-article',
    trust: 68,
    license: 'editorial',
    container: 'main, article, .entry-content',
    pages: [
      'https://www.greataiprompts.com/prompts/best-chatgpt-prompts/',
      'https://www.greataiprompts.com/prompts/chatgpt-prompts-for-writing/',
      'https://www.greataiprompts.com/prompts/chatgpt-prompts-for-marketing/',
    ],
    limit: 60,
  },
  {
    key: 'promptingguide',
    name: 'Prompt Engineering Guide (DAIR.AI)',
    home_url: 'https://www.promptingguide.ai',
    kind: 'html-article',
    trust: 92,
    license: 'MIT',
    container: 'main, article',
    pages: [
      'https://www.promptingguide.ai/prompts/classification/sentiment',
      'https://www.promptingguide.ai/prompts/coding/mysql-query',
      'https://www.promptingguide.ai/prompts/reasoning/indirect-reasoning',
      'https://www.promptingguide.ai/prompts/text-summarization/explain-concept',
      'https://www.promptingguide.ai/prompts/information-extraction/extract-model-names',
      'https://www.promptingguide.ai/prompts/question-answering/closed-domain',
    ],
    defaultTags: ['prompt-engineering'],
    limit: 40,
  },
  {
    key: 'yokoffing-prompts',
    name: 'ChatGPT Prompts (yokoffing)',
    home_url: 'https://github.com/yokoffing/ChatGPT-Prompts',
    kind: 'markdown',
    trust: 83,
    license: 'MIT',
    fetchUrl: 'https://raw.githubusercontent.com/yokoffing/ChatGPT-Prompts/main/README.md',
    anchorBase: 'https://github.com/yokoffing/ChatGPT-Prompts',
    limit: 80,
  },
  {
    key: 'ms-prompts-for-edu',
    name: 'Microsoft Prompts for Edu',
    home_url: 'https://github.com/microsoft/prompts-for-edu',
    kind: 'github-files',
    trust: 90,
    license: 'MIT',
    repo: 'microsoft/prompts-for-edu',
    branch: 'main',
    pathPattern: '/Prompts/.+\\.MD$',
    limit: 40,
  },
  {
    key: 'semrush',
    name: 'Semrush Blog',
    home_url: 'https://www.semrush.com',
    kind: 'html-article',
    trust: 74,
    license: 'editorial',
    container: 'main, article',
    pages: [
      'https://www.semrush.com/blog/chatgpt-prompts/',
    ],
    defaultTags: ['marketing'],
    limit: 50,
  },
  {
    key: 'writesonic',
    name: 'Writesonic Blog',
    home_url: 'https://writesonic.com',
    kind: 'html-article',
    trust: 70,
    license: 'editorial',
    container: 'main, article, .entry-content',
    pages: [
      'https://writesonic.com/blog/chatgpt-prompts',
    ],
    limit: 60,
  },
  {
    key: 'hubspot',
    name: 'HubSpot Blog',
    home_url: 'https://blog.hubspot.com',
    kind: 'html-article',
    trust: 76,
    license: 'editorial',
    container: 'main, article, .blog-post__body',
    pages: [
      'https://blog.hubspot.com/marketing/chatgpt-prompts',
    ],
    defaultTags: ['marketing'],
    limit: 50,
  },
  {
    key: 'openai-cookbook',
    name: 'OpenAI Cookbook',
    home_url: 'https://cookbook.openai.com',
    kind: 'github-files',
    trust: 96,
    license: 'MIT',
    repo: 'openai/openai-cookbook',
    branch: 'main',
    pathPattern: '^examples/.+\\.md$',
    limit: 40,
    defaultTags: ['openai', 'official'],
  },
  {
    key: 'dair-ai-guide',
    name: 'Prompt Engineering Guide — full guide (DAIR.AI)',
    home_url: 'https://www.promptingguide.ai',
    kind: 'github-files',
    trust: 94,
    license: 'MIT',
    repo: 'dair-ai/Prompt-Engineering-Guide',
    branch: 'main',
    pathPattern: '^pages/.+\\.en\\.mdx$',
    limit: 60,
    defaultTags: ['prompt-engineering'],
  },
  {
    key: 'learnprompting',
    name: 'Learn Prompting',
    home_url: 'https://learnprompting.org',
    kind: 'html-article',
    trust: 88,
    license: 'CC-BY-SA',
    container: 'main, article',
    pages: [
      'https://learnprompting.org/docs/basics/roles',
      'https://learnprompting.org/docs/basics/few_shot',
      'https://learnprompting.org/docs/basics/formalizing',
      'https://learnprompting.org/docs/basics/combining_techniques',
      'https://learnprompting.org/docs/intermediate/chain_of_thought',
      'https://learnprompting.org/docs/intermediate/zero_shot_cot',
      'https://learnprompting.org/docs/intermediate/self_consistency',
      'https://learnprompting.org/docs/advanced_applications/writing_essay',
    ],
    defaultTags: ['prompt-engineering', 'education'],
    limit: 60,
  },
  {
    key: 'fabric-patterns',
    name: 'Fabric Patterns (danielmiessler)',
    home_url: 'https://github.com/danielmiessler/fabric',
    kind: 'github-files',
    trust: 90,
    license: 'MIT',
    repo: 'danielmiessler/fabric',
    branch: 'main',
    pathPattern: '^data/patterns/.+/system\\.md$',
    titleFromFolder: true,
    limit: 120,
    defaultTags: ['fabric'],
  },
  {
    key: 'awesome-cursorrules',
    name: 'Awesome CursorRules',
    home_url: 'https://github.com/PatrickJS/awesome-cursorrules',
    kind: 'github-files',
    trust: 82,
    license: 'CC0-1.0',
    repo: 'PatrickJS/awesome-cursorrules',
    branch: 'main',
    pathPattern: '^rules/.+\\.mdc?$',
    titleFromFolder: true,
    limit: 60,
    defaultTags: ['cursor', 'developers'],
  },
  {
    key: 'leaked-system-prompts',
    name: 'Leaked System Prompts (jujumilk3)',
    home_url: 'https://github.com/jujumilk3/leaked-system-prompts',
    kind: 'github-files',
    trust: 76,
    license: 'MIT',
    repo: 'jujumilk3/leaked-system-prompts',
    branch: 'main',
    pathPattern: '\\.md$',
    limit: 50,
    defaultTags: ['system-prompt'],
  },
];
